name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: resource group name
        required: true
        default: rg-training-dev-francecentral-001
        type: string
      region:
        description: region of resource group
        required: true
        default: francecentral
        type: string
      workspace:
        description: workspace name
        required: true
        default: mlw-training-dev-001
        type: string
      instance_name:
        description: compute instance name
        required: true
        default: def-cluster
        type: string
  
jobs:
  build_env_and_train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    # - name: add azure ML extension
    #   uses: Azure/CLI@v1
    #   with:
    #     inlineScript: | 
    #       #!/bin/bash
    #       az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_2}}

    - name: create a resource group on Azure
      uses: Azure/CLI@v1
      with:
        inlineScript: | 
          # #!/bin/bash
          # if $(az group exists --name ${{ github.event.inputs.resource_group }}) ; then
          #   echo "Azure resource group already exists, skipping creation..."
          # else
          az group create --name ${{ github.event.inputs.resource_group }} --location ${{ github.event.inputs.region }}
          # az configure --defaults group=${{ github.event.inputs.resource_group }}
          # echo "Azure resource group created"
          # fi

    - name: create a ML workspace on Azure
      uses: Azure/CLI@v1
      with:
        inlineScript: | 
          #!/bin/bash
          az extension add -n ml -y
          if $(az workspace exists --name ${{ github.event.inputs.workspace }}); then
              echo "workspace already exists with this name"
          else
            az ml workspace create --name ${{ github.event.inputs.workspace }} --resource-group ${{ github.event.inputs.resource_group }}
            az configure --defaults workspace=${{ github.event.inputs.workspace }}
            echo "done! workspace is created"
          fi
    - name: create a compute instance
      run: |
        az ml compute create --name ${{github.event.inputs.instance_name}} --size STANDARD_DS11_V2 --max-instances 2 --type AmlCompute --resource-group ${{github.event.inputs.resource_group}} --workspace-name ${{github.event.inputs.workspace}}
    - name: add a data asset to azure workspace
      run: |
        az ml data create --name diabetes-dev-folder --path "experimentation/data" --resource-group ${{github.event.inputs.resource_group}} --workspace-name ${{github.event.inputs.workspace}}
    - name: create an Azure ML job
      run: |
        az ml job create --file "src/job.yml" --resource-group ${{github.event.inputs.resource_group}} --workspace-name ${{github.event.inputs.workspace}}