name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: resource group name
        required: true
        default: def_resource_group
        type: string
      workspace:
        description: workspace name
        required: true
        default: workspace2
        type: string
      instance_name:
        description: compute instance name
        required: true
        default: instance1
        type: string
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: create azure workspace and setting it as default
      run: |
        az ml workspace create --name ${{github.event.inputs.workspace}} --resource-group "${{github.event.inputs.resource_group}}"        
        echo 'Hey2'
        az configure --defaults workspace=${{github.event.inputs.workspace}}
    - name: create a compute instance
      run: |
        az ml compute create --name ${{github.event.inputs.instance_name}} --size STANDARD_DS11_V2 --type ComputeInstance  --resource-group ${{github.event.inputs.resource_group}} --workspace-name ${{github.event.inputs.workspace}}
    - name: add a data asset to azure workspace
      run: |
        az ml data create --name diabetes-dev-folder --path "/home/alimassoud/onedrive/MLOps/MLOps_MS_Chal0/experimentation/data"
        echo 'HELLOO'
    - name: create an Azure ML job
      run: |
        az ml job create --file "/home/alimassoud/onedrive/MLOps/MLOps_MS/src/job.yml"